# Generated by Django 5.1.6 on 2025-02-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapi', '0003_discount_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='stripe_tax_rate_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
